# Generated by Django 4.2.3 on 2023-07-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('is_online', models.BooleanField(null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('difficulty', models.PositiveIntegerField(verbose_name='Сложность')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('course', models.ManyToManyField(null=True, to='reviews.course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(verbose_name='Общая оценка')),
                ('interest', models.PositiveIntegerField(verbose_name='Интерес к предмету')),
                ('benefit', models.PositiveIntegerField(verbose_name='Польза от предмета')),
                ('understanding', models.PositiveIntegerField(verbose_name='Общедоступность курса')),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.course')),
            ],
        ),
    ]
